---
name: Events
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited] # only run against these types of pull request
  push:
    branches: # only run on push to specified branches
      - main
      # - "dev-*"   covers dev-new dev-experimental etc
      # - "feat/**" covers feat/new feat/new/experimental etc
    paths-ignore:
      - "README.md" # workflow runs on push to branches above, but not if this file was changed
permissions: read-all
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJson(github.event) }}"
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying project :)"
