---
name: Initial Workflow
on: workflow_dispatch # manual triggering
jobs:
  initial_job: # user defined name
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, world!"
      - name: Print goodbye
        run: echo "Goodbye!"
