---
name: Deployment with secrets
on:
  push:
    branches:
      - main
      - dev
permissions: read-all
env: # can be defined at workflow | job | step level
  MONGODB_DB_NAME: gha-demo # workflow level hard-coded variable
  MONGODB_CLUSTER_ADDRESS: cluster.mongodb.net
  MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }} # added via Repository -> Secrets and variables -> Actions
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }} # added via Repository -> Secrets and variables -> Actions
jobs:
  test:
    env:
      PORT: 8000
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package.lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run Tests
        run: npm run test
      - name: Output Information
        run: echo "MONGODB_USERNAME - ${{ env.MONGODB_USERNAME }}" # will not be printed as MONGODB_USERNAME is now secret
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying application..."
          echo "Connecting to MONGODB_CLUSTER_ADDRESS - ${{ env.MONGODB_CLUSTER_ADDRESS }}"
